import { MedusaService } from "@medusajs/framework/utils"
import CategoryCustomAttribute from "./models/category-custom-attribute"
import ProductCustomAttribute from "./models/product-custom-attribute"

const models = {
  CategoryCustomAttribute,
  ProductCustomAttribute,
}

type Models = typeof models

// @ts-ignore - MedusaService dynamically generates methods based on models
class CustomAttributeService extends MedusaService(models) {
  async getCategoryAttributes(categoryId: string) {
    // @ts-ignore - method generated by MedusaService
    return await this.listCategoryCustomAttributes({
      category_id: categoryId,
      deleted_at: null,
    })
  }

  async getAttributesByCategoryIds(categoryIds: string[]) {
    if (!categoryIds || categoryIds.length === 0) {
      return []
    }
    // @ts-ignore - method generated by MedusaService
    const attributes = await this.listCategoryCustomAttributes({
      category_id: categoryIds,
      deleted_at: null,
    })
    // First id in the list is the leaf category — its attributes are "own",
    // everything else is inherited from an ancestor.
    const leafId = categoryIds[0]
    return attributes.map((attr: any) => ({
      ...attr,
      inherited: attr.category_id !== leafId,
      source_category_id: attr.category_id,
    }))
  }

  async createCategoryAttribute(data: {
    label: string
    type: string
    unit?: string | null
    category_id: string
    is_standard?: boolean
    sort_order?: number
  }) {
    const key = this.generateKey(data.label)
    // @ts-ignore - method generated by MedusaService
    return await this.createCategoryCustomAttributes({
      ...data,
      key,
      unit: data.unit ?? null,
      is_standard: data.is_standard ?? false,
      sort_order: data.sort_order ?? 0,
    })
  }

  async updateCategoryAttribute(
    id: string,
    data: {
      label?: string
      type?: string
      unit?: string | null
      sort_order?: number
      deleted_at?: string
    }
  ) {
    const updateData: Record<string, any> = { ...data }
    if (data.label) {
      updateData.key = this.generateKey(data.label)
    }
    // @ts-ignore - method generated by MedusaService
    return await this.updateCategoryCustomAttributes([{ id, ...updateData }])
  }

  async createProductAttribute(data: {
    product_id: string
    category_custom_attribute_id: string
    value: string
    value_numeric?: number | null
    value_file?: string | null
  }) {
    // @ts-ignore - method generated by MedusaService
    return await this.createProductCustomAttributes(data)
  }

  async updateProductAttribute(
    id: string,
    data: {
      value?: string
      value_numeric?: number | null
      value_file?: string | null
      deleted_at?: string
    }
  ) {
    // @ts-ignore - method generated by MedusaService
    return await this.updateProductCustomAttributes([{ id, ...data }])
  }

  async getProductAttributes(productId: string) {
    // @ts-ignore - method generated by MedusaService
    return await this.listProductCustomAttributes({
      product_id: productId,
      deleted_at: null,
    }, {
      relations: ["category_custom_attribute"],
    })
  }

  private generateKey(label: string): string {
    return label
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_|_$/g, "")
  }
}

export default CustomAttributeService
